/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author ivana
 */
public class KonversiSuhuFrame extends javax.swing.JFrame {

    public KonversiSuhuFrame() {
        initComponents();  // Inisialisasi komponen yang dihasilkan oleh NetBeans
        
        // Membuat ButtonGroup untuk RadioButton
        ButtonGroup suhuGroup = new ButtonGroup();
        suhuGroup.add(keFahrenheitButton);
        suhuGroup.add(keCelciusButton);
        suhuGroup.add(keReamurButton);
        suhuGroup.add(keKelvinButton);
    
        // Menambahkan ActionListener untuk tombol konversi
        konversiButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                konversiSuhu();  // Memanggil metode konversi suhu saat tombol ditekan
            }
        });
        
        // Menambahkan KeyListener untuk input suhu
        inputSuhu.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                // Membatasi input hanya angka dan titik
                char c = e.getKeyChar();
                if (!Character.isDigit(c) && c != '.') {
                    e.consume();
                }
            }
        });
    }

    // Metode untuk konversi suhu
    private void konversiSuhu() {
        try {
            // Ambil nilai suhu dari inputSuhu
            double suhu = Double.parseDouble(inputSuhu.getText());
            double hasilKonversi = 0.0;
            String satuanSuhu = "";

            // Periksa button yang dipilih dan lakukan konversi
            if (keFahrenheitButton.isSelected()) {
                hasilKonversi = suhu * 9 / 5 + 32;
                satuanSuhu = "°F";  // Fahrenheit
            } else if (keCelciusButton.isSelected()) {
                hasilKonversi = suhu;  // Jika sudah dalam Celcius
                satuanSuhu = "°C";  // Celsius
            } else if (keReamurButton.isSelected()) {
                hasilKonversi = suhu * 4 / 5;
                satuanSuhu = "°R";  // Reamur
            } else if (keKelvinButton.isSelected()) {
                hasilKonversi = suhu + 273.15;
                satuanSuhu = "K";  // Kelvin
            }

            // Menampilkan hasil konversi dan satuan suhu di labelHasil
            hasilLabel.setText(String.format("%.2f %s", hasilKonversi, satuanSuhu));

        } catch (NumberFormatException e) {
            // Menangani kesalahan jika input tidak valid
            hasilLabel.setText("Input tidak valid. Masukkan angka.");
        }
    }

    // Rumus konversi suhu
    private double konversiKeFahrenheit(double suhu, String suhuMasuk) {
        switch (suhuMasuk) {
            case "Celcius": return (suhu * 9/5) + 32;
            case "Reamur": return (suhu * 9/4) + 32;
            case "Kelvin": return (suhu - 273.15) * 9/5 + 32;
            default: return suhu;
        }
    }

    private double konversiKeCelcius(double suhu, String suhuMasuk) {
        switch (suhuMasuk) {
            case "Fahrenheit": return (suhu - 32) * 5/9;
            case "Reamur": return suhu * 5/4;
            case "Kelvin": return suhu - 273.15;
            default: return suhu;
        }
    }

    private double konversiKeReamur(double suhu, String suhuMasuk) {
        switch (suhuMasuk) {
            case "Celcius": return suhu * 4/5;
            case "Fahrenheit": return (suhu - 32) * 4/9;
            case "Kelvin": return (suhu - 273.15) * 4/5;
            default: return suhu;
        }
    }

    private double konversiKeKelvin(double suhu, String suhuMasuk) {
        switch (suhuMasuk) {
            case "Celcius": return suhu + 273.15;
            case "Fahrenheit": return (suhu - 32) * 5/9 + 273.15;
            case "Reamur": return (suhu * 5/4) + 273.15;
            default: return suhu;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputSuhu = new javax.swing.JTextField();
        suhuMasukComboBox = new javax.swing.JComboBox<>();
        konversiButton = new javax.swing.JButton();
        hasilLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        keKelvinButton = new javax.swing.JRadioButton();
        keReamurButton = new javax.swing.JRadioButton();
        keCelciusButton = new javax.swing.JRadioButton();
        keFahrenheitButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Masukkan Suhu");

        suhuMasukComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin" }));
        suhuMasukComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                suhuMasukComboBoxItemStateChanged(evt);
            }
        });
        suhuMasukComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuMasukComboBoxActionPerformed(evt);
            }
        });

        konversiButton.setText("Konversi");

        keKelvinButton.setText("Kelvin");

        keReamurButton.setText("Reamur");

        keCelciusButton.setText("Celcius");

        keFahrenheitButton.setText("Fahrenheit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(keFahrenheitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keCelciusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keReamurButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keKelvinButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keFahrenheitButton)
                    .addComponent(keCelciusButton)
                    .addComponent(keReamurButton)
                    .addComponent(keKelvinButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Hasil :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suhuMasukComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(konversiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hasilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suhuMasukComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hasilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(konversiButton)
                        .addComponent(jLabel2)))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suhuMasukComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuMasukComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuMasukComboBoxActionPerformed

    private void suhuMasukComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_suhuMasukComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuMasukComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField inputSuhu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton keCelciusButton;
    private javax.swing.JRadioButton keFahrenheitButton;
    private javax.swing.JRadioButton keKelvinButton;
    private javax.swing.JRadioButton keReamurButton;
    private javax.swing.JButton konversiButton;
    private javax.swing.JComboBox<String> suhuMasukComboBox;
    // End of variables declaration//GEN-END:variables
}